apiVersion: networking.k8s.io/v1 # Ingress 리소스의 API 버전
kind: Ingress # 리소스 타입: Ingress
metadata:
  name: k8s-test-ingress # Ingress 리소스 이름
  namespace: k8s-test-app # 속한 네임스페이스
  annotations: # Nginx Ingress Controller 동작을 위한 설정 값
    nginx.ingress.kubernetes.io/rewrite-target: / # 요청 경로를 백엔드에 전달할 때 /로 변환
    nginx.ingress.kubernetes.io/ssl-redirect: 'false' # HTTP 요청 시 HTTPS로 강제 리다이렉트 하지 않음

spec:
  ingressClassName: nginx # 사용할 Ingress Controller 클래스 이름 (여기서는 nginx)
  rules: # 라우팅 규칙 정의
    - host: 127.0.0.1 # 접근할 도메인 (브라우저에서 이 주소로 접속)
      http:
        paths:
          - path: / # 요청 경로 (여기서는 모든 요청 /)
            pathType: Prefix # 경로 타입: Prefix → /로 시작하는 모든 경로 매칭
            backend:
              service:
                name: k8s-test-service # 연결할 쿠버네티스 Service 이름
                port:
                  number: 80 # 서비스의 포트 번호 (서비스 정의에서 targetPort와 연결)
