apiVersion: v1
kind: Secret
metadata:
  name: k8s-test-secret-dev
  namespace: k8s-test-app-dev
type: Opaque
data:
  # base64 encoded values
  NODE_ENV: ZGV2ZWxvcG1lbnQ= # development
  PORT: MzAwMQ== # 3001
  APP_NAME: TmVzdEpTIEFwcCAoRGV2KQ== # NestJS App (Dev)
  API_VERSION: MS4wLjA= # 1.0.0
  LOG_LEVEL: ZGVidWc= # debug
  DB_HOST: bG9jYWxob3N0 # localhost
  DB_PORT: NTQzMg== # 5432
  DB_NAME: bmVzdGpzX2Rldg== # nestjs_dev
  DB_USER: ZGV2X3VzZXI= # dev_user
  DB_PASSWORD: ZGV2X3Bhc3N3b3Jk # dev_password
  REDIS_HOST: bG9jYWxob3N0 # localhost
  REDIS_PORT: NjM3OQ== # 6379
  EXTERNAL_API_URL: aHR0cHM6Ly9hcGktZGV2LmV4YW1wbGUuY29t # https://api-dev.example.com
  EXTERNAL_API_KEY: ZGV2LWFwaS1rZXk= # dev-api-key
  ENABLE_METRICS: dHJ1ZQ== # true
  METRICS_PORT: OTA5MA== # 9090
  API_PREFIX: L2FwaS92MQ== # /api/v1
  JWT_SECRET: ZGV2LXNlY3JldC1rZXk= # dev-secret-key
  JWT_EXPIRES_IN: MWg= # 1h
  LOG_FILE: bG9ncy9hcHAtZGV2LmxvZw== # logs/app-dev.log
