apiVersion: v1
kind: Secret
metadata:
  name: k8s-test-secret-prod
  namespace: k8s-test-app
type: Opaque
data:
  # base64 encoded values
  NODE_ENV: cHJvZHVjdGlvbg== # production
  PORT: MzAwMQ== # 3001
  APP_NAME: TmVzdEpTIEFwcCAoUHJvZCk= # NestJS App (Prod)
  API_VERSION: MS4wLjA= # 1.0.0
  LOG_LEVEL: aW5mbw== # info
  DB_HOST: cHJvZC1kYi5leGFtcGxlLmNvbQ== # prod-db.example.com
  DB_PORT: NTQzMg== # 5432
  DB_NAME: bmVzdGpzX3Byb2Q= # nestjs_prod
  DB_USER: cHJvZF91c2Vy # prod_user
  DB_PASSWORD: cHJvZC1zZWN1cmUtcGFzc3dvcmQ= # prod-secure-password
  REDIS_HOST: cHJvZC1yZWRpcy5leGFtcGxlLmNvbQ== # prod-redis.example.com
  REDIS_PORT: NjM3OQ== # 6379
  EXTERNAL_API_URL: aHR0cHM6Ly9hcGkuZXhhbXBsZS5jb20= # https://api.example.com
  EXTERNAL_API_KEY: cHJvZC1hcGkta2V5 # prod-api-key
  ENABLE_METRICS: dHJ1ZQ== # true
  METRICS_PORT: OTA5MA== # 9090
  API_PREFIX: L2FwaS92MQ== # /api/v1
  JWT_SECRET: cHJvZC1zdXBlci1zZWN1cmUtc2VjcmV0LWtleQ== # prod-super-secure-secret-key
  JWT_EXPIRES_IN: MjRo # 24h
  LOG_FILE: bG9ncy9hcHAtcHJvZC5sb2c= # logs/app-prod.log
